---
# tasks file for cob.fn1
- name: Install Factory Number One dependencies.
  action: apt pkg={{ item }} state=present
  with_items:
    - nodejs
    - npm

#the version of node installed by packages is typically out of date
- name: clear npm cache
  shell: npm cache clean -f

#sudo npm install -g n
- name: Install node via npm globally
  npm: name=n global=yes

- name: Update node to the latest stable version
  shell: n stable

- name: Update npm to the latest version
  npm: name=npm global=yes state=latest

  
# something funky is going on with getting modules available globally
# there may be a bug with ansible <= 2.1
# https://github.com/ansible/ansible-modules-extras/issues/1375
# state=present first may fix, even if it is ugly
# via:
# https://github.com/geerlingguy/ansible-role-nodejs/commit/459f3fed968a6b49eb0fcfe9542050433bab0a9d
# https://github.com/geerlingguy/ansible-role-nodejs/issues/17
  
- name: Make sure gulp-cli is installed globally
  npm: name=gulp-cli global=yes state=present

- name: Update gulp-cli to the latest
  npm: name=gulp-cli global=yes state=latest

- name: Make sure node-sass is installed globally
  npm: name=node-sass global=yes state=present

- name: Update node-sass to the latest
  npm: name=node-sass global=yes state=latest

  
- name: check if repository has already been checked out
  stat: path='{{ fn1_path }}'
  register: check

- name: Pull latest version of repository from git source
  git: repo=https://github.com/City-of-Bloomington/factory-number-one.git version=refactor dest='{{ fn1_path }}'
  when: not check.stat.exists

- name: Ensure paths are accessible by webserver
  file: path={{ fn1_path }} state=directory owner=www-data group=staff recurse=yes mode=2770

# get any other dependencies
# (takes a while!!)

# either need to run as an unprivileged user (non-root)
# or need to supply --unsafe_perm flag
# node-sass checks this
# https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#cannot-find-module-rootinstalljs

# seems that the previous command to update file permissions
# does not always complete in time for the next command
- name: Waiting for previous command to take effect
  pause: seconds=30

#- shell: npm install
#  args:
#    chdir: "{{ fn1_path }}"
- name: Use NPM to get all dependencies for building FN1
  npm: path="{{ fn1_path }}"
  become_user: "{{ ansible_ssh_user }}"
#  unsafe_perm: yes

- name: Do the initial build of FN1
  shell: gulp
  args:
    chdir: "{{ fn1_path }}"



    