---
# User must be in place before the MAKE INSTALL happens
- name: Add Nagios Group
  group:
    name: nagios
    system: yes
    state: present

- name: Add Nagios User
  user:
    name: nagios
    comment: 'Nagios User'
    system: yes
    state: present

- name: Build Nagios NRPE (x86_64)
  shell: 'cd {{ src_dir }}/{{ nrpe_version }};{{ item }}'
  with_items:
    - ./configure --enable-command-args --with-ssl=/usr/lib/x86_64-linux-gnu 
    - make
    - make install
  when: ansible_architecture == "x86_64" 

- name: Build Nagios NRPE (i386)
  shell: 'cd {{ src_dir }}/{{ nrpe_version }};{{ item }}'
  with_items:
    - ./configure --enable-command-args 
    - make
    - make install
  when: ansible_architecture != "x86_64" 

- name: Build Nagios Plugins
  shell: 'cd {{ src_dir }}/{{ nagios_plugins_version.stdout }};{{ item }}'
  with_items:
    - ./configure
    - make
    - make install


