---
- name: Download NRPE (Linux)
  get_url: 
    url: 'http://packages.bloomington.in.gov/NRPE/{{ nrpe_version }}.tar.gz'
    dest: '{{ src_dir }}'
  when: ansible_distribution == 'Ubuntu'

- name: Uncompress NRPE tar file
  unarchive:
    src: '{{ src_dir }}/{{ nrpe_version }}.tar.gz'
    dest: '{{ src_dir }}'
    copy: no 
  when: ansible_distribution == 'Ubuntu'

- name: Download NRPE (Windows)
  get_url:
    url: 'http://packages.bloomington.in.gov/NRPE/nrpe_nt.tar.gz'
    
- name: Get Nagios Plugins Version
  shell: curl https://www.nagios.org/downloads/nagios-plugins/ | egrep -o 'nagios-plugins-[0-9.]+.tar.gz<' | egrep -o 'nagios-plugins-[0-9.]+[^.t]'
  register: nagios_plugins_version

- name: Download Latest Nagios Plugins
  get_url:
    url: 'http://www.nagios-plugins.org/download/{{ nagios_plugins_version.stdout }}.tar.gz'
    dest: '{{ src_dir }}'

- name: Uncompress Nagios Plugins tar file
  unarchive:
    src: '{{ src_dir }}/{{ nagios_plugins_version.stdout }}.tar.gz'
    dest: '{{ src_dir }}'
    copy: no
