---
- name: Allow Nagios to NRPE port (Linux)
  ufw:
    from_ip: '{{ nagios_ip }}'
    to_port: '{{ nrpe_service_port }}'
    rule: allow
    state: enabled
  when: ansible_os_family == 'Linux'
  
- name: Allow Nagios to NRPE port (Windows)
  win_firewall_rule:
    action: allow
    direction: in
    state: present
    name: 'NRPE'
    desscription: 'Allow Nagios to NRPE service'
    profile: 'Public,Private' 
    remoteip: '{{ nagios_ip }}'
    localport: '{{ nrpe_service_port }}'
  when: ansible_os_family == 'Windows'

