---
- include: linux-download.yml
  tags: [ download_nrpe ]
  when: ansible_os_family == 'Linux' 

- include: windows-download.yml
  tags: [ download_nrpe ]
  when: ansible_os_family == 'Windows' 

- include: windows-install.yml
  when: ansible_os_family == 'Windows'

- include: build.yml
  tags: [ build_nrpe ] 
  when: ansible_os_family == 'Linux' 

- include: firewall.yml
  tags: [ firewall ]

- include: post-install.yml
  tags: [ postinstall_nrpe ]
  when: ansible_os_family == 'Linux'
