---
- name: Download MegaRaid Utility
  get_url:
    url: 'http://packages.bloomington.in.gov/Megacli/megacli'
    dest: '{{ megacli_path }}'

- name: Change permissions (megacli)
  file:
    path: '{{ megacli_path }}/megacli'
    owner: root
    group: root
    mode: 0755

- name: Copy MegaRaid plugin
  template:
    src: check_megaraid_vds.j2
    dest: /usr/local/nagios/libexec/check_megaraid_vds
    owner: nagios
    group: nagios
    mode: 0755

- name: Create Megacli Sudo Entry
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    line: "{{ nrpe_user }}  ALL=NOPASSWD: /usr/local/sbin/megacli -LDInfo -lALL -aALL"
    validate: 'visudo -cf %s'
    state: present
