---
- name: Copy default init script
  template:
    src: nrpe.init.j2
    dest: '/etc/init.d/{{ nrpe_service_name }}'
    owner: root
    group: root
    mode: 0755

- name: Create NRPE etc folder
  file:
    path: /usr/local/nagios/etc
    state: directory
    owner: nagios
    group: nagios
    mode: 0755

- name: Create configuration file
  template:
    src: nrpe.cfg.j2 
    dest: /usr/local/nagios/etc/nrpe.cfg
    owner: nagios
    group: nagios
    mode: 0644
  notify: restart nrpe

- name: Set NRPE service conditions
  service:
    name: '{{ nrpe_service_name }}'
    enabled: '{{ nrpe_service_enabled }}'
    state: '{{ nrpe_service_state }}'

    

