---
galaxy_info:
  author: Cliff Ingham <inghamn@bloomington.in.gov>
  description:
  company: City of Bloomington
  license: GPLv3
  min_ansible_version: 1.2

dependencies:
    - City-of-Bloomington.linux
