#
# Ansible playbook for setting up a common base server for COB
# based off of:
# http://city-of-bloomington.github.io/LinuxInstallHelp/Ubuntu-Installation.html
#

---
- hosts: all
  remote_user: username
  become: yes

  tasks:

    #want first call to apt to run with update cache set to yes
    - name: Install ntp 
      apt: name=ntp state=present update_cache=yes
      tags: ntp

    - name: Set TimeZone in /etc/localtime
      #http://askubuntu.com/questions/323131/setting-timezone-from-terminal
      command: /usr/bin/timedatectl set-timezone America/Indiana/Indianapolis
      tags: ntp
      notify: restart ntp

    - name: Start the ntp service
      service: name=ntp state=started enabled=yes
      tags: ntp


    ##
    # Apt package installation of required software.
    - name: General | Install required packages.
      action: apt pkg={{ item }} state=present
      tags: common
      with_items:
        - build-essential
        - autoconf
        - libncurses5-dev
        - libssl-dev
        - emacs
        - zip
        - unzip
        - subversion
        - git
        - libxml2-dev
        - libxslt-dev
        - libldap2-dev
        - libtidy-dev
        - libcurl4-openssl-dev
        - imagemagick
        - libjpeg-dev
        - libpng-dev
        - libxpm-dev
        - libfreetype6-dev
        - libpcre3-dev
        - libicu-dev

    - name: Set default shell for user accounts
      command: useradd -D -s /bin/bash
      tags: common


    #http://docs.ansible.com/ansible/ufw_module.html
    - name: Enable the firewall
      ufw: state=enabled policy=deny
      tags: firewall

    - name: Configure the firewall (ssh)
      ufw: rule=allow port=ssh
      tags: firewall

    - name: Configure the firewall (http)
      ufw: rule=allow port=http
      tags: firewall
      
    - name: Configure the firewall (https)
      ufw: rule=allow port=https
      tags: firewall




  handlers:
    - name: restart ntp
      service: name=ntp state=restarted

  