#
# Ansible playbook for setting up a mysql server for COB
# based off of:
# http://city-of-bloomington.github.io/LinuxInstallHelp/MySQL.html
#

---
- hosts: dbservers
  remote_user: username
  become: yes

  tasks:
    - name: Install Mysql packages
      action: apt pkg={{ item }} state=installed
      tags: mysql
      with_items:
       - mysql-server
       - mysql-client
       - libmysqlclient-dev
       - python-mysqldb

    - name: Create Mysql configuration file
      template: src=templates/my.cnf.j2 dest=/etc/mysql/my.cnf
      notify: 
      - restart mysql


    - name: stop mysql
      service: name=mysql state=stopped

    - name: Remove old databases
      command: rm -Rf /var/lib/mysql    
      tags: mysql

    - name: Initialize databases
      command: /usr/bin/mysql_install_db
      tags: mysql

    - name: Update database permissions
      command: chown -R mysql /var/lib/mysql
      tags: mysql

    - name: Start Mysql Service
      service: name=mysql state=started enabled=yes


    #TODO:
    # configure Database user accounts according to documentation


    #TODO:
    #consider other mysql configurations here:

    # - name: insert iptables rule
    #   lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
    #               insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
    #   notify: restart iptables

    # - name: Create Application Database
    #   mysql_db: name={{ dbname }} state=present

    # - name: Create Application DB User
    #   mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present

    #     Status API Training Shop Blog About Pricing 
    
  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

  