#
# Ansible playbook for setting up PHP on an apache server for COB
# based off of:
# http://city-of-bloomington.github.io/LinuxInstallHelp/PHP.html
#
#should have already happened with apache installation, but...
- name: create build directory
  file: path={{ src_dir }}/ state=directory mode=0755

    #using same approach here as apache (until better solution found)
    #download the source files locally and then transfer

    #download php from:
    #http://www.php.net/downloads.php

    #Then download apr and apr-util from:
    #http://apr.apache.org/download.cgi

    #place them in the ./downloads directory on local machine:
    #cd downloads/
    #mv ~/Downloads/php-* .

- name: copy local php source file and extract
  unarchive: src=downloads/{{ php_version }}.tar.gz dest={{ src_dir }}

- name: Check ubuntu version
  stat: path=/lib/x86_64-linux-gnu
  register: check_path

- name: Configure PHP (32bit)
  shell: 'cd {{ php_dir }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/php --with-apxs2=/usr/local/apache/bin/apxs --without-pear --disable-short-tags --disable-cgi --enable-mbstring --with-curl --enable-exif --with-ldap --with-zlib --with-mysql=/var/lib/mysql --with-mysqli=/usr/bin/mysql_config --with-pdo-mysql=/usr --with-openssl --enable-soap --with-tidy --with-xsl --with-gd --enable-gd-native-ttf --with-jpeg-dir=/usr --with-freetype-dir=/usr --enable-intl --with-gettext --with-libdir=/lib/i386-linux-gnu --with-mysql-sock=/run/mysqld/mysqld.sock
  when: not check_path.stat.exists

- name: Configure php (64bit)
  shell: 'cd {{ php_dir }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/php --with-apxs2=/usr/local/apache/bin/apxs --without-pear --disable-short-tags --disable-cgi --enable-mbstring --with-curl --enable-exif --with-ldap --with-zlib --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-pdo-mysql=/usr --with-openssl --enable-soap --with-tidy --with-xsl --with-gd --enable-gd-native-ttf --with-jpeg-dir=/usr --with-freetype-dir=/usr --enable-intl --with-gettext --with-libdir=/lib/x86_64-linux-gnu --with-mysql-sock=/run/mysqld/mysqld.sock
  when: check_path.stat.exists      
      
- name: Build php
  shell: 'cd {{ php_dir }};{{ item }}'
  with_items:
    - make
    - make install

#http://docs.ansible.com/ansible/lineinfile_module.html
- name: update httpd.conf
  #lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="LoadModule php5_module        Modules/libphp5.so" line="{{ item }}" backrefs=yes
  lineinfile: dest=/usr/local/apache/conf/httpd.conf state=present insertafter="LoadModule php5_module" line="AddType application/x-httpd-php .php"

#- name: create php lib dir
#  file: path=/usr/local/php/lib/ state=directory mode=0755

- name: Create php.ini file (development)
  template: src=templates/php.ini-development.j2 dest=/usr/local/php/lib/php.ini
  when: production == 'No'

- name: Create php.ini file (production)
  template: src=templates/php.ini-production.j2 dest=/usr/local/php/lib/php.ini
  when: production == 'Yes'

- name: restart apache service
  service: name=apache state=restarted
