---
- name: "Deploy LDAP access file"
  template:
    src: ldap_access.conf.j2
    dest: "{{ ldap_access_file }}"
    mode: 0600
    owner: root

- name: "Deploy User_setup XML config"
  template:
    src: user_setup.conf.j2
    dest: /usr/local/sbin/user_setup.xml
    mode: 0600
    owner: root
