---
galaxy_info:
  author: Eric Morrow 
  description: Role to build php from source
  company: City of Bloomington, IN 
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2

dependencies: 
