---
# defaults file for cob.build-php
cob_php_src_dir: /usr/local/src

# List major version only
cob_php_version: php-5.6

cob_php_mirror_server: http://us1.php.net

#'Yes' for php.ini-production
production: 'Yes'
