---
# tasks file for cob.linux-common
- command: apt-get update
  tags: [ apt_update, apt_upgrade ]

- command: apt-get upgrade -y
  tags: apt_upgrade

- name: Install common packages
  action: apt pkg={{ item }} state=present
  tags: common
  with_items: cob_common_packages

- name: Setup Firewall
  include: firewall.yml
  tags: firewall

- name: Setup NTP
  include: ntp.yml
  tags: ntp

- name: Setup VIM
  include: vim.yml
  tags: vim

- name: Setup Nano
  include: nano.yml
  tags: nano
