---
- name: Install NTP 
  apt: 
    pkg: ntp 
    state: '{{ ntp_pkg_state }}' 
    update_cache: no  
    cache_valid_time: 3600

- name: Set Timezone 
  file:
    src: '/usr/share/zoneinfo/{{ ntp_timezone }}'
    dest: /etc/localtime
    state: link
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

- name: Setup NTP Configuration File
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: Configure NTP Service 
  service:
    name: ntp 
    state: '{{ ntp_service_state }}'
    enabled: '{{ ntp_service_enabled }}'


# Use Ubuntu's ntp server as a fallback.
