---
# tasks file for cob.apache

- name: Install apache and related packages
  apt:
    name: "{{ item }}"
    state: present
  tags: apache
  # defined in defaults/main.yml
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: Add mod_rewrite configuration
  copy: src=rewrite.conf dest=/etc/apache2/mods-available/rewrite.conf force=no

- apache2_module: state=present name=rewrite
- apache2_module: state=present name=alias
- apache2_module: state=present name=wsgi

- file: path=/srv/sites/master state=directory
- file: path=/srv              state=directory owner=www-data group=staff mode=2770 recurse=yes
- command: cp /var/www/html/index.html /srv/sites/master

- name: Update default configuration
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644

- service: name=apache2 state=restarted

# TODO:
#add users to staff group, or add server to domain for Active Directory accounts
- user: name={{ ansible_ssh_user }} groups=staff,sudo

- name: Configure the firewall (http)
  ufw: rule=allow port=http
