---
# tasks file for cob.apache

- name: Install apache and related packages
  apt: 
    name: "{{ item }}" 
    state: present
  tags: apache
  #defined in defaults/main.yml
  with_items:
    - apache2

    - imagemagick
    - libjpeg-dev
    - libpng-dev
    - libxpm-dev
    - libfreetype6-dev
    
    - libncurses5-dev
    - gettext
    - libxml2-dev
    - libxslt-dev
    - libldap2-dev
    - libtidy-dev
    - libcurl4-openssl-dev
    - libpcre3-dev
    - libicu-dev

    #for python web apps
    - libapache2-mod-wsgi    
    
- apache2_module: state=present name=rewrite

- apache2_module: state=present name=alias

# enables the Apache2 module "wsgi"
- apache2_module: state=present name=wsgi

  
#make sure paths exist
#sudo chgrp -R staff /srv
#sudo chmod -R g+w /srv
#sudo chmod -R g+s /srv
#verify 2750 is equivalent to above:
#- file: path=/srv state=directory group=staff recurse=yes mode=2770
- file: path=/srv state=directory owner=www-data group=staff mode=2770
- file: path=/srv/sites state=directory owner=www-data group=staff recurse=yes mode=2770

#TODO:
#add users to staff group, or add server to domain for Active Directory accounts
- user: name={{ ansible_ssh_user }} groups=staff,sudo

- name: Configure the firewall (http)
  ufw: rule=allow port=http

