---
# tasks file for cob.apache

- name: Install apache and related packages
  apt: 
    name: "{{ item }}" 
    state: present
  tags: apache
  #defined in defaults/main.yml
  with_items:
    - apache2

    - imagemagick
    - libjpeg-dev
    - libpng-dev
    - libxpm-dev
    - libfreetype6-dev
    
    - libncurses5-dev
    - gettext
    - libxml2-dev
    - libxslt-dev
    - libldap2-dev
    - libtidy-dev
    - libcurl4-openssl-dev
    - libpcre3-dev
    - libicu-dev

- apache2_module: state=present name=rewrite

- apache2_module: state=present name=alias
    
#make sure paths exist
#sudo chgrp -R staff /srv
#sudo chmod -R g+w /srv
#sudo chmod -R g+s /srv
#verify 2750 is equivalent to above:
- file: path=/srv state=directory group=staff recurse=yes mode=2750
- file: path=/srv/sites state=directory group=staff recurse=yes mode=2750

