#check for earlier copies:
- name: Create Apache HTTPD Directory Fact
  set_fact: cob_apache_httpd_dir={{ cob_apache_src_dir }}/{{ cob_apache_httpd_file.stdout }}

- name: Check if apr path exists
  stat: path={{ cob_apache_httpd_dir }}/srclib/apr
  register: check_apr_path

- name: Move apr to httpd/srclib
  command: mv {{ cob_apache_src_dir }}/{{ cob_apache_apr_file.stdout }} {{ cob_apache_httpd_dir }}/srclib/apr
  when: not check_apr_path.stat.exists

- name: Check if apr util path exists
  stat: path={{ cob_apache_httpd_dir }}/srclib/apr-util
  register: check_apr_util_path

- name: Move apr-util to httpd/srclib
  command: mv {{ cob_apache_src_dir }}/{{ cob_apache_aprutil_file.stdout}} {{ cob_apache_httpd_dir }}/srclib/apr-util
  when: not check_apr_util_path.stat.exists

- name: Check for previous build
  stat: path={{ cob_apache_httpd_dir }}/config.log
  register: apache_config_log

#adapted via:
#http://serverfault.com/questions/573843/ansible-playbook-not-working-trying-to-run-make-configure-with-complex-switche
- name: Build httpd with apr
  shell: 'cd {{ cob_apache_httpd_dir }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/apache --with-included-apr --enable-proxy --enable-so --enable-ssl --enable-expires --enable-headers --enable-rewrite --enable-cgi --disable-status --disable-userdir --disable-autoindex --with-mpm=prefork
    - make
    - make install
  when: not apache_config_log.stat.exists

