#check for earlier copies:
- name: Create Apache HTTPD Directory Fact
  set_fact: cob_apache_httpd_dir={{ cob_apache_src_dir }}/{{ cob_apache_httpd_file.stdout }}

- name: Check if apr path exists
  stat: path={{ cob_apache_httpd_dir }}/srclib/apr
  register: check_apr_path

- name: Move apr to httpd/srclib
  command: mv {{ cob_apache_src_dir }}/{{ cob_apache_apr_file.stdout }} {{ cob_apache_httpd_dir }}/srclib/apr
  when: not check_apr_path.stat.exists

- name: Check if apr util path exists
  stat: path={{ cob_apache_httpd_dir }}/srclib/apr-util
  register: check_apr_util_path

- name: Move apr-util to httpd/srclib
  command: mv {{ cob_apache_src_dir }}/{{ cob_apache_aprutil_file.stdout}} {{ cob_apache_httpd_dir }}/srclib/apr-util
  when: not check_apr_util_path.stat.exists

- name: Check for previous build
  stat: path={{ cob_apache_httpd_dir }}/config.log
  register: apache_config_log

#TODO:
#not sure if there is a way to check that this step has happened previously
#and skip it in that case

#adapted via:
#http://serverfault.com/questions/573843/ansible-playbook-not-working-trying-to-run-make-configure-with-complex-switche

- name: Build httpd with apr
  shell: 'cd {{ cob_apache_httpd_dir }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/apache --with-included-apr --enable-proxy --enable-so --enable-ssl --enable-expires --enable-headers --enable-rewrite --enable-cgi --disable-status --disable-userdir --disable-autoindex --with-mpm=prefork
    - make
    - make install
  when: not apache_config_log.stat.exists

# http://docs.ansible.com/ansible/user_module.html
- name: Add apache user
  user: name=apache comment="Apache User" home=/usr/local/apache system=yes shell=/dev/null



    #update apache configuration file:
    #
    #with this approach, updates to the configuration file
    #in new versions of apache of would be included
    #
    #running in to problems with this approach for lines with quotes in them
    #it's close, and sed may be an alternative to fixing this
    #for now I need to move on to a working installation

    #http://docs.ansible.com/ansible/lineinfile_module.html
    #http://docs.ansible.com/ansible/YAMLSyntax.html
    #backrefs=yes avoid lines being added at the end of the file
    #http://stackoverflow.com/questions/19390600/ansible-lineinfile-duplicates-line

    # - name: update httpd.conf Load modules
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="#{{ item }}" line="{{ item }}" backrefs=yes
    #   with_items:
    #     - LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
    #     - LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
    #     - LoadModule ssl_module modules/mod_ssl.so
    #     - LoadModule rewrite_module modules/mod_rewrite.so

    # - name: update httpd.conf User
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="User daemon" line="User apache" backrefs=yes

    # - name: update httpd.conf Group
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="Group daemon" line="Group apache" backrefs=yes

    # - name: update httpd.conf DocumentRoot
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp='DocumentRoot "/usr/local/apache/htdocs"' line='DocumentRoot "/srv/sites/master"' backrefs=yes

    # - name: update httpd.conf DocumentRoot (2)
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp='<Directory "/usr/local/apache/htdocs">' line='<Directory "/srv/sites/master">' backrefs=yes

    # - name: update httpd.conf DirectoryIndex
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="DirectoryIndex index.html" line="    DirectoryIndex index.php index.html" backrefs=yes

    # - name: update httpd.conf ErrorLog
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp='ErrorLog "logs/error_log"' line='ErrorLog "/var/log/httpd/error.log"' backrefs=yes

    # - name: update httpd.conf CustomLog common
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf backrefs=yes regexp="   CustomLog \"logs/access_log\" common" line="    #CustomLog \"logs/access_log\" common"

    # - name: update httpd.conf CustomLog combined
    #   lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp='    #CustomLog "logs/access_log" combined' line='    CustomLog "/var/log/httpd/access.log" combined' backrefs=yes
