- name: Cleanup downloaded files
  file: path=files/downloads/{{ item }} state=absent 
  with_items:
    - "{{ cob_apache_httpd_file.stdout }}"
    - "{{ cob_apache_apr_file.stdout }}"
    - "{{ cob_apache_aprutil_file.stdout }}"

# just copying a local template over instead of updating in place:
- name: Create apache configuration file
  template: src=httpd.conf.j2 dest=/usr/local/apache/conf/httpd.conf
  notify: restart apache 

- name: create /var/log/httpd directory
  file: path=/var/log/httpd state=directory mode=0755

- name: create serve directory
  # create a directory if it doesn't exist
  file: path={{ cob_apache_serve_dir }} state=directory mode=0775

#check for earlier copies:
- name: Check if {{ cob_apache_serve_dir }}/master path exists
  stat: path={{ cob_apache_serve_dir }}/master
  register: check_path

- name: Copy htdocs to {{ cob_apache_serve_dir}}/master
  command: cp -R /usr/local/apache/htdocs {{ cob_apache_serve_dir }}/master
  when: not check_path.stat.exists

- name: update ownership
  command: chown -R apache:staff {{ cob_apache_serve_dir }}

- name: update group as writeable
  command: chmod -R g+w {{ cob_apache_serve_dir }} 

- name: ensure websites.conf file exists
  command: touch /usr/local/apache/conf/websites.conf

    #http://docs.ansible.com/ansible/lineinfile_module.html
- name: update apachectl
  lineinfile: dest=/usr/local/apache/bin/apachectl state=present insertbefore=BOF line="{{ item }}"
  with_items:
    #this is reverse of what it should be in the file
    - "### END INIT INFO"
    - "# Description:       Start the web server"
    - "# Short-Description: Apache web server"
    - "# X-Interactive:     true"
    - "# Default-Stop:      0 1 6"
    - "# Default-Start:     2 3 4 5"
    - "# Required-Stop:     $local_fs $remote_fs $network $syslog $named"
    - "# Required-Start:    $local_fs $remote_fs $network $syslog $named"
    - "# Provides:          apache"
    - "### BEGIN INIT INFO"

- name: link to apachectl
  file: src=/usr/local/apache/bin/apachectl dest=/etc/init.d/{{ cob_apache_service_name}} state=link

- name: Create logrotate configuration file
  template: src=logrotate.apache.j2 dest=/etc/logrotate.d/apache

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ cob_apache_service_name }}"
    state: "{{ cob_apache_service_state }}"
    enabled: yes
    pattern: /usr/local/apache/bin/httpd
