# just copying a local template over instead of updating in place:
- name: Update base httpd.conf
  lineinfile: dest=/usr/local/apache/conf/httpd.conf regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
  - { regexp: 'LoadModule socache_shmcb_module', line: 'LoadModule socache_shmcb_module modules/mod_socache_shmcb.so' }
  - { regexp: 'LoadModule slotmem_shm_module',   line: 'LoadModule slotmem_shm_module modules/mod_slotmem_shm.so' }
  - { regexp: 'LoadModule ssl_module',           line: 'LoadModule ssl_module modules/mod_ssl.so' }
  - { regexp: 'LoadModule rewrite_module',       line: 'LoadModule rewrite_module modules/mod_rewrite.so' }
  - { regexp: '^User [a-z]+$',  line: 'User apache' }
  - { regexp: '^Group [a-z]+$', line: 'Group apache' }
  - { regexp: '^DocumentRoot\s+\"(/usr/local/apache/htdocs|/srv/sites/master)\"', line: 'DocumentRoot \"/srv/sites/master\"' }
  - { regexp: '^<Directory\s+\"(/usr/local/apache/htdocs|/srv/sites/master)\"',   line: '<Directory   \"/srv/sites/master\">' }
  - { regexp: '^ErrorLog ', line: 'ErrorLog /var/log/httpd/error.log' }
  - { regexp: 'CustomLog [\"a-z_/]+ common',     line: '    #CustomLog \"logs/access_log\" common' }
  - { regexp: 'CustomLog [\"a-z_/\.]+ combined', line: '    CustomLog \"/var/log/httpd/access.log\" combined' }

- name: Create websites.conf
  command: touch /usr/local/apache/conf/websites.conf

- name: Add websites.conf to httpd.conf
  lineinfile: dest=/usr/local/apache/conf/httpd.conf insertafter=EOF line='Include conf/websites.conf'

- name: create /var/log/httpd directory
  file: path=/var/log/httpd state=directory mode=0755

- name: create serve directory
  # create a directory if it doesn't exist
  file: path={{ cob_apache_serve_dir }} state=directory mode=0775

#check for earlier copies:
- name: Check if {{ cob_apache_serve_dir }}/master path exists
  stat: path={{ cob_apache_serve_dir }}/master
  register: check_path

- name: Copy htdocs to {{ cob_apache_serve_dir}}/master
  command: cp -R /usr/local/apache/htdocs {{ cob_apache_serve_dir }}/master
  when: not check_path.stat.exists

- name: update ownership
  command: chown -R apache:staff {{ cob_apache_serve_dir }}

- name: update group as writeable
  command: chmod -R g+w {{ cob_apache_serve_dir }}

    #http://docs.ansible.com/ansible/lineinfile_module.html
- name: update apachectl
  lineinfile: dest=/usr/local/apache/bin/apachectl state=present insertbefore=BOF line="{{ item }}"
  with_items:
    #this is reverse of what it should be in the file
    - "### END INIT INFO"
    - "# Description:       Start the web server"
    - "# Short-Description: Apache web server"
    - "# X-Interactive:     true"
    - "# Default-Stop:      0 1 6"
    - "# Default-Start:     2 3 4 5"
    - "# Required-Stop:     $local_fs $remote_fs $network $syslog $named"
    - "# Required-Start:    $local_fs $remote_fs $network $syslog $named"
    - "# Provides:          apache"
    - "### BEGIN INIT INFO"

- name: link to apachectl
  file: src=/usr/local/apache/bin/apachectl dest=/etc/init.d/{{ cob_apache_service_name}} state=link

- name: Create logrotate configuration file
  template: src=logrotate.apache.j2 dest=/etc/logrotate.d/apache

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ cob_apache_service_name }}"
    state: "{{ cob_apache_service_state }}"
    enabled: yes
    pattern: /usr/local/apache/bin/httpd
