- name: "Install dependencies" 
  apt:
    state: build-dep
    name: samba

- name: "Configure Samba"
  shell: cd /usr/local/src/{{ samba_package.stdout }} && ./configure 

- name: "Install Samba"
  shell: cd /usr/local/src/{{ samba_package.stdout }} && make && make install

- name: "Create ld.so.conf.d Samba file"
  lineinfile:
    create: yes
    dest: /etc/ld.so.conf.d/samba
    insertafter: EOF
    line: "/usr/local/samba/lib"

- name: "Run ldconfig"
  shell: ldconfig

- name: "Link Samba binaries to /usr/sbin"
  shell: ln -fs /usr/local/samba/sbin/* /usr/sbin
    
- name: "Link Samba binaries to /usr/bin"
  shell: ln -fs /usr/local/samba/bin/* /usr/bin

- name: "Install Samba Init Script"
  file:
    src: samba.init
    dest: /etc/init.d/samba

- name: "Set Samba to start automatically"
  service:
    enabled: yes
    name: samba 
