---
- name: "Install Winbind Init Script"
  file:
    src: winbind.init
    dest: /etc/init.d/winbind

- name: "Set Winbind to start automatically"
  service:
    enabled: yes
    name: winbind 

- name: "Get NSS modules"
  shell: cd /usr/local/samba/lib && ls libnss_*
  register: nss_modules

- name: "Link Winbind NSS module (64-bit)"
  file:
    state: link
    src: "/usr/local/samba/lib/{{ item }}"
    dest: "/usr/lib/x86_64-linux-gnu/{{ item }}"
    force: yes
  with_items: "{{ nss_modules.stdout_lines }}"
  when: ansible_architecture == 'x86_64'
    
- name: "Link Winbind NSS module (32-bit)"
  file:
    state: link
    src: "/usr/local/samba/lib/{{ item }}"
    dest: "/usr/lib/i386-linux-gnu/{{ item }}"
    force: yes
  with_items: "{{ nss_modules.stdout_lines }}"
  when: ansible_architecture == 'i386'

- name: "Update nsswitch.conf"
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    dest: /etc/nsswitch.conf
  with_items: 
    - { regexp: '^passwd:', line: 'passwd:		files winbind' }
    - { regexp: '^group:', line: 'group:		files winbind' }
    - { regexp: '^shadow:', line: 'shadow:		files' }
