---
# vars file for cob.fn1

#relative symbolic links in other packages
#expect fn1 to be at the same level as other packages
fn1_path: /srv/factory-number-one

fn1_base: assets

fn1_apache_config: /etc/apache2/sites-available/fn1.conf