---
# defaults file for cob.linux-common
ntp_servers:
  - ntp.bloomington.in.gov
  - cob.bloomington.in.gov
ntp_timezone: 'America/Indiana/Indianapolis'

cob_common_packages: [build-essential, autoconf, libssl-dev, emacs, zip, unzip, subversion, git]
