---
# defaults file for cob.linux-common
ntp_servers:
  - cob.bloomington.in.gov
  - ntp.bloomington.in.gov

ntp_restrictions: 
  - 127.0.0.1

ntp_fallback_server: pool.ntp.org
ntp_timezone: 'America/Indiana/Indianapolis'
ntp_service_state: started
ntp_pkg_state: present
ntp_service_enabled: yes 

nagios_ip: 10.20.20.27

src_dir: /usr/local/src

