- name: Install MySQL
  action: apt pkg={{ item }} state=present
  tags: apache
  with_items:
  - mysql-client
  - mysql-server

- name: Add entries to Mysql configuration file
  lineinfile: dest=/etc/mysql/my.cnf insertafter="skip-external-locking" line={{ item }}
  with_items:
  - 'innodb_file_per_table=1'
  - 'default_storage_engine=InnoDB'
  - 'character_set_server=utf8'
  notify:
  - restart mysql
  tags: mysql

- name: stop mysql
  service: name=mysql state=stopped
  tags: mysql

- name: Remove old databases
  command: rm -Rf /var/lib/mysql
  tags: mysql

- name: Initialize databases
  command: /usr/bin/mysql_install_db
  tags: mysql

- name: Update database permissions
  command: chown -R mysql /var/lib/mysql
  tags: mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
  tags: mysql


    #TODO:
    # configure Database user accounts according to documentation


    #TODO:
    #consider other mysql configurations here:

    # - name: insert iptables rule
    #   lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
    #               insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
    #   notify: restart iptables

    # - name: Create Application Database
    #   mysql_db: name={{ dbname }} state=present

    # - name: Create Application DB User
    #   mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present

    #     Status API Training Shop Blog About Pricing

