---
- name: Check ubuntu version
  stat: path=/lib/x86_64-linux-gnu
  register: check_path

- name: Configure PHP (32bit)
  shell: 'cd {{ cob_php_src_dir }}/{{ cob_php_full_version.stdout }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/php --with-apxs2=/usr/local/apache/bin/apxs --without-pear --disable-short-tags --disable-cgi --enable-mbstring --with-curl --enable-exif --with-ldap --with-zlib --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-pdo-mysql=/usr --with-openssl --enable-soap --with-tidy --with-xsl --with-gd --enable-gd-native-ttf --with-jpeg-dir=/usr --with-freetype-dir=/usr --enable-intl --with-gettext --with-libdir=/lib/i386-linux-gnu
  when: not check_path.stat.exists

- name: Configure php (64bit)
  shell: 'cd {{ cob_php_src_dir}}/{{ cob_php_full_version.stdout }};{{ item }}'
  with_items:
    - ./configure --prefix=/usr/local/php --with-apxs2=/usr/local/apache/bin/apxs --without-pear --disable-short-tags --disable-cgi --enable-mbstring --with-curl --enable-exif --with-ldap --with-zlib --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-pdo-mysql=/usr --with-openssl --enable-soap --with-tidy --with-xsl --with-gd --enable-gd-native-ttf --with-jpeg-dir=/usr --with-freetype-dir=/usr --enable-intl --with-gettext --with-libdir=/lib/x86_64-linux-gnu
  when: check_path.stat.exists

- name: Build php
  shell: 'cd {{ cob_php_src_dir}}/{{ cob_php_full_version.stdout }};{{ item }}'
  with_items:
    - make
    - make install

