- hosts: all
  become: yes
  vars_files:
    #these should be picked up automatically if using ansible 2.x
    #but for 1.x this works:
    - ../group_vars/ureport.yml
    - ../group_vars/vault/ureport.yml

  vars:    
    #mysql variables... these are specific to this playbook
    
    #mysql_root_password: "{{ ureport_db_password }}"
    mysql_databases:
      - name: "{{ ureport_db_name }}"
        #encoding: latin1
        #collation: latin1_general_ci
    mysql_users:
      - name: "{{ ureport_db_username }}"
        host: "%"
        password: "{{ ureport_db_password }}"
        priv: "{{ ureport_db_name }}.*:ALL"

    #https://github.com/geerlingguy/ansible-role-solr
    solr_version: "5.5.3"
    solr_home: /srv/solr
    solr_cores:
      - ureport
      
  roles:
    - cob.linux-common

    - cob.apache
    
    - cob.php    
    
    # via:
    # https://github.com/geerlingguy/ansible-role-composer
    # this requires using ansible-galaxy to pull down the role first:
    # sudo ansible-galaxy install geerlingguy.composer
    - geerlingguy.composer

    # this requires using ansible-galaxy to pull down the role first:
    # sudo ansible-galaxy install geerlingguy.mysql    
    - geerlingguy.mysql            

    #install solr
    
    # via:
    # https://github.com/geerlingguy/ansible-role-java
    # this requires using ansible-galaxy to pull down the role first:
    # sudo ansible-galaxy install geerlingguy.java
    - geerlingguy.java

    # via:
    # https://github.com/geerlingguy/ansible-role-solr
    # this requires using ansible-galaxy to pull down the role first:
    # sudo ansible-galaxy install geerlingguy.solr
    - geerlingguy.solr
    
    - cob.fn1

    - cob.ureport

    