---
# vars file for cob.ureport

ureport_path: /srv/sites/ureport
ureport_base: ureport

#these should be defined elsewhere (these are not sane defaults)
#ureport_db_name: ureport
#ureport_db_username: user
#ureport_db_password: pass

#ureport_apache_config: /etc/apache2/sites-available/000-default.conf
ureport_apache_config: /etc/apache2/sites-available/ureport.conf
