---
- name: Download Solr
  get_url:
    url: "{{ solr_download_url }}"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    creates: "{{ solr_workspace }}/{{ solr_filename }}/CHANGES.txt"
    copy: no

- name: Create Solr installation directory
  file:
    path: "{{ solr_install_dir }}"
    state: directory

- name: Run Solr installation script.
  shell: >
    {{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh
    {{ solr_workspace }}/{{ solr_filename }}.tgz
    -i {{ solr_install_dir }}
    -d {{ solr_home }}
    creates={{ solr_install_dir }}/solr/bin/solr
