---
- name: Make sure Java is installed
  apt:
    name: default-jre
    state: present

- name: Check if Solr is already installed
  stat: path=/etc/init.d/solr
  register: solr_service

- include: install.yml
  when: solr_service.stat.exists == False